const REQUEST_API_DATA = 'REQUEST_API_DATA';
const LOGIN_API_SUCCESS = 'LOGIN_API_SUCCESS';
const REQUEST_API_FAILURE = 'REQUEST_API_FAILURE';

export {REQUEST_API_DATA, LOGIN_API_SUCCESS, REQUEST_API_FAILURE};
