const REQUEST_API_DATA = 'REQUEST_API_DATA';
const LOGIN_API_SUCCESS = 'LOGIN_API_SUCCESS';
const STOP_LOADER = 'STOP_LOADER';
const SET_INITIAL_APP_OPEN = 'SET_INITIAL_APP_OPEN';
const SET_STATE_DISTRICT_DATA = 'SET_STATE_DISTRICT_DATA';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export {
  REQUEST_API_DATA,
  LOGIN_API_SUCCESS,
  STOP_LOADER,
  SET_INITIAL_APP_OPEN,
  SET_STATE_DISTRICT_DATA,
  LOGOUT_SUCCESS,
};
